# Site settings
author: Tachi Shuttlesworth 
title: Tachi's Blog
header-img: img/home-bg.png
email: tshuttlesworth@gmail.com
copyright_name: Tachi Shuttlesworth 
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Blogs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tshuttles

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
